local-es    ansible_host=10.10.99.102
local-m0    ansible_host=10.10.99.210
local-m1    ansible_host=10.10.99.211
local-m2    ansible_host=10.10.99.212
local-w0    ansible_host=10.10.99.220

[elastic]
local-es

[docker_swarm_manager]
local-m0
local-m1
local-m2

[docker_swarm_worker]
local-w0

[docker_swarm_node]
local-m0
local-m1
local-m2
local-w0

[all:vars]
elastic_server=10.10.99.102
es_heap_size=1g
