local-swarm-m0     ansible_host=10.100.199.210
local-swarm-m1     ansible_host=10.100.199.211
local-swarm-m2     ansible_host=10.100.199.212
local-swarm-n0     ansible_host=10.100.199.220
local-elasticstack ansible_host=10.100.199.102

[elastic]
local-elasticstack

[docker_swarm_manager]
local-swarm-m0
local-swarm-m1
local-swarm-m2

[docker_swarm_worker]
local-swarm-n0

[docker_swarm_node]
local-swarm-m0
local-swarm-m1
local-swarm-m2
local-swarm-n0

[all:vars]
elastic_server=10.100.199.102
es_heap_size=1g
