- name: Add Elasticsearch Key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
  tags: [elasticsearch]

- name: Add Elasticsearch repository and update apt cache
  apt_repository:
    repo: deb http://artifacts.elastic.co/packages/5.x/apt stable main
    update_cache: yes
    state: present
  tags: [elasticsearch]

- name: Elasticsearch installed
  apt:
    name: elasticsearch
    state: present
    force: yes
  tags: [elasticsearch]

- name: Copy Elasticsearch default template
  template: 
    src: elasticsearch.default.template
    dest: /etc/default/elasticsearch
    owner: root
    group: root
    mode: 0544
  register: default_result
  tags: [elasticsearch]

- name: Copy other files
  copy: src={{ item }}
        dest=/etc/elasticsearch/
  with_items:
    - elasticsearch.yml
  register: config_result
  tags: [elasticsearch]

- name: Enable the Elasticsearch service and start it.
  service:
    name: elasticsearch.service
    state: started
    enabled: yes
  tags: [elasticsearch]

- name: Systemd reload
  command: systemctl daemon-reload
  when: (default_result|changed) or (config_result|changed)
  tags: [elasticsearch]

- name: Service is restarted
  service:
    name=elasticsearch
    state=restarted
  when: (default_result|changed) or (config_result|changed)
  tags: [elasticsearch]
